services:
  storage:
    image: jaguanas/simplerpc-storage:0.1.0
    ports:
      - "5000:5000"
  baker:
    image: jaguanas/simplerpc-baker:0.1.0
    environment:
      STORAGE_URL: http://storage:5000/simplerpc
    depends_on:
      - storage
  farmer:
    image: jaguanas/simplerpc-farmer:0.1.0
    environment:
      STORAGE_URL: http://storage:5000/simplerpc
    depends_on:
      - storage